In [2]:
import numpy as np
li = [1,2,3, 'z']

a = np.array(li)
print(a)
b = np.arange(15)
b

['1' '2' '3' 'z']


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
import numpy as np
m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]
print(m3)

[[[[0 1 0]
   [0 1 1]
   [1 0 0]]

  [[0 0 1]
   [0 1 1]
   [1 1 0]]

  [[1 0 0]
   [1 1 0]
   [1 1 0]]]


 [[[1 0 0]
   [0 1 0]
   [0 0 1]]

  [[1 1 1]
   [0 0 0]
   [1 1 0]]

  [[0 0 1]
   [0 1 1]
   [0 1 1]]]


 [[[1 1 0]
   [0 1 1]
   [0 0 0]]

  [[1 1 0]
   [0 1 0]
   [1 0 1]]

  [[0 1 1]
   [0 0 1]
   [1 0 0]]]]


m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

In [32]:
m=m3.ndim
print(m)
a=m3.size
print(a)
b=m3.shape
print(b)
c=m3.dtype
print(c)
d=m3.itemsize
print(d)
e=m3.nbytes
print(e)

4
81
(3, 3, 3, 3)
int32
4
324
